/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class Attribute {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Attribute(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Attribute obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_Attribute(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getAttributeID() {
    return eufeJNI.Attribute_getAttributeID(swigCPtr, this);
  }

  public float getValue() {
    return eufeJNI.Attribute_getValue(swigCPtr, this);
  }

  public float getInitialValue() {
    return eufeJNI.Attribute_getInitialValue(swigCPtr, this);
  }

  public boolean isStackable() {
    return eufeJNI.Attribute_isStackable(swigCPtr, this);
  }

  public boolean highIsGood() {
    return eufeJNI.Attribute_highIsGood(swigCPtr, this);
  }

  public void setValue(float value) {
    eufeJNI.Attribute_setValue(swigCPtr, this, value);
  }

  public float dec(float value) {
    return eufeJNI.Attribute_dec(swigCPtr, this, value);
  }

  public float inc(float value) {
    return eufeJNI.Attribute_inc(swigCPtr, this, value);
  }

  public String getAttributeName() {
    return eufeJNI.Attribute_getAttributeName(swigCPtr, this);
  }

}
