/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class BoostersList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BoostersList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BoostersList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_BoostersList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BoostersList() {
    this(eufeJNI.new_BoostersList(), true);
  }

  public long size() {
    return eufeJNI.BoostersList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return eufeJNI.BoostersList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    eufeJNI.BoostersList_clear(swigCPtr, this);
  }

  public void add(Booster x) {
    eufeJNI.BoostersList_add(swigCPtr, this, Booster.getCPtr(x), x);
  }

  public Booster get(int i) {
    long cPtr = eufeJNI.BoostersList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Booster(cPtr, false);
  }

}
