/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class ControlTower extends Item {
  private long swigCPtr;

  protected ControlTower(long cPtr, boolean cMemoryOwn) {
    super(eufeJNI.ControlTower_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ControlTower obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_ControlTower(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Structure addStructure(int typeID) {
    long cPtr = eufeJNI.ControlTower_addStructure(swigCPtr, this, typeID);
    return (cPtr == 0) ? null : new Structure(cPtr, false);
  }

  public void removeStructure(Structure structure) {
    eufeJNI.ControlTower_removeStructure(swigCPtr, this, Structure.getCPtr(structure), structure);
  }

  public StructuresList getStructures() {
    return new StructuresList(eufeJNI.ControlTower_getStructures(swigCPtr, this), true);
  }

  public boolean canFit(Structure structure) {
    return eufeJNI.ControlTower_canFit(swigCPtr, this, Structure.getCPtr(structure), structure);
  }

  public DamagePattern getDamagePattern() {
    return new DamagePattern(eufeJNI.ControlTower_getDamagePattern(swigCPtr, this), false);
  }

  public void setDamagePattern(DamagePattern damagePattern) {
    eufeJNI.ControlTower_setDamagePattern(swigCPtr, this, DamagePattern.getCPtr(damagePattern), damagePattern);
  }

  public float getPowerGridUsed() {
    return eufeJNI.ControlTower_getPowerGridUsed(swigCPtr, this);
  }

  public float getTotalPowerGrid() {
    return eufeJNI.ControlTower_getTotalPowerGrid(swigCPtr, this);
  }

  public float getCpuUsed() {
    return eufeJNI.ControlTower_getCpuUsed(swigCPtr, this);
  }

  public float getTotalCpu() {
    return eufeJNI.ControlTower_getTotalCpu(swigCPtr, this);
  }

  public Resistances getResistances() {
    return new Resistances(eufeJNI.ControlTower_getResistances(swigCPtr, this), false);
  }

  public Tank getTank() {
    return new Tank(eufeJNI.ControlTower_getTank(swigCPtr, this), false);
  }

  public Tank getEffectiveTank() {
    return new Tank(eufeJNI.ControlTower_getEffectiveTank(swigCPtr, this), false);
  }

  public HitPoints getHitPoints() {
    return new HitPoints(eufeJNI.ControlTower_getHitPoints(swigCPtr, this), false);
  }

  public HitPoints getEffectiveHitPoints() {
    return new HitPoints(eufeJNI.ControlTower_getEffectiveHitPoints(swigCPtr, this), false);
  }

  public float getShieldRecharge() {
    return eufeJNI.ControlTower_getShieldRecharge(swigCPtr, this);
  }

  public float getWeaponDps() {
    return eufeJNI.ControlTower_getWeaponDps(swigCPtr, this);
  }

  public float getWeaponVolley() {
    return eufeJNI.ControlTower_getWeaponVolley(swigCPtr, this);
  }

}
