/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class DamagePattern {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DamagePattern(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DamagePattern obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_DamagePattern(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DamagePattern() {
    this(eufeJNI.new_DamagePattern__SWIG_0(), true);
  }

  public DamagePattern(float em, float thermal, float kinetic, float explosive) {
    this(eufeJNI.new_DamagePattern__SWIG_1(em, thermal, kinetic, explosive), true);
  }

  public void setEmAmount(float value) {
    eufeJNI.DamagePattern_emAmount_set(swigCPtr, this, value);
  }

  public float getEmAmount() {
    return eufeJNI.DamagePattern_emAmount_get(swigCPtr, this);
  }

  public void setThermalAmount(float value) {
    eufeJNI.DamagePattern_thermalAmount_set(swigCPtr, this, value);
  }

  public float getThermalAmount() {
    return eufeJNI.DamagePattern_thermalAmount_get(swigCPtr, this);
  }

  public void setKineticAmount(float value) {
    eufeJNI.DamagePattern_kineticAmount_set(swigCPtr, this, value);
  }

  public float getKineticAmount() {
    return eufeJNI.DamagePattern_kineticAmount_get(swigCPtr, this);
  }

  public void setExplosiveAmount(float value) {
    eufeJNI.DamagePattern_explosiveAmount_set(swigCPtr, this, value);
  }

  public float getExplosiveAmount() {
    return eufeJNI.DamagePattern_explosiveAmount_get(swigCPtr, this);
  }

}
