/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class EffectsList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EffectsList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EffectsList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_EffectsList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EffectsList() {
    this(eufeJNI.new_EffectsList(), true);
  }

  public long size() {
    return eufeJNI.EffectsList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return eufeJNI.EffectsList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    eufeJNI.EffectsList_clear(swigCPtr, this);
  }

  public void add(Effect x) {
    eufeJNI.EffectsList_add(swigCPtr, this, Effect.getCPtr(x), x);
  }

  public Effect get(int i) {
    long cPtr = eufeJNI.EffectsList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Effect(cPtr, false);
  }

}
