/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class Gang extends Item {
  private long swigCPtr;

  protected Gang(long cPtr, boolean cMemoryOwn) {
    super(eufeJNI.Gang_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Gang obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_Gang(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CharactersList getPilots() {
    return new CharactersList(eufeJNI.Gang_getPilots(swigCPtr, this), true);
  }

  public Character addPilot() {
    long cPtr = eufeJNI.Gang_addPilot__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Character(cPtr, false);
  }

  public Character addPilot(Character character) {
    long cPtr = eufeJNI.Gang_addPilot__SWIG_1(swigCPtr, this, Character.getCPtr(character), character);
    return (cPtr == 0) ? null : new Character(cPtr, false);
  }

  public void removePilot(Character character) {
    eufeJNI.Gang_removePilot(swigCPtr, this, Character.getCPtr(character), character);
  }

  public Character getFleetBooster() {
    long cPtr = eufeJNI.Gang_getFleetBooster(swigCPtr, this);
    return (cPtr == 0) ? null : new Character(cPtr, false);
  }

  public Character getWingBooster() {
    long cPtr = eufeJNI.Gang_getWingBooster(swigCPtr, this);
    return (cPtr == 0) ? null : new Character(cPtr, false);
  }

  public Character getSquadBooster() {
    long cPtr = eufeJNI.Gang_getSquadBooster(swigCPtr, this);
    return (cPtr == 0) ? null : new Character(cPtr, false);
  }

  public void setFleetBooster(Character fleetBooster) {
    eufeJNI.Gang_setFleetBooster(swigCPtr, this, Character.getCPtr(fleetBooster), fleetBooster);
  }

  public void setWingBooster(Character wingBooster) {
    eufeJNI.Gang_setWingBooster(swigCPtr, this, Character.getCPtr(wingBooster), wingBooster);
  }

  public void setSquadBooster(Character squadBooster) {
    eufeJNI.Gang_setSquadBooster(swigCPtr, this, Character.getCPtr(squadBooster), squadBooster);
  }

  public void removeFleetBooster() {
    eufeJNI.Gang_removeFleetBooster(swigCPtr, this);
  }

  public void removeWingBooster() {
    eufeJNI.Gang_removeWingBooster(swigCPtr, this);
  }

  public void removeSquadBooster() {
    eufeJNI.Gang_removeSquadBooster(swigCPtr, this);
  }

}
