/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class ImplantsList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ImplantsList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImplantsList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_ImplantsList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ImplantsList() {
    this(eufeJNI.new_ImplantsList__SWIG_0(), true);
  }

  public ImplantsList(long n) {
    this(eufeJNI.new_ImplantsList__SWIG_1(n), true);
  }

  public long size() {
    return eufeJNI.ImplantsList_size(swigCPtr, this);
  }

  public long capacity() {
    return eufeJNI.ImplantsList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    eufeJNI.ImplantsList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return eufeJNI.ImplantsList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    eufeJNI.ImplantsList_clear(swigCPtr, this);
  }

  public void add(Implant x) {
    eufeJNI.ImplantsList_add(swigCPtr, this, Implant.getCPtr(x), x);
  }

  public Implant get(int i) {
    long cPtr = eufeJNI.ImplantsList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Implant(cPtr, false);
  }

  public void set(int i, Implant val) {
    eufeJNI.ImplantsList_set(swigCPtr, this, i, Implant.getCPtr(val), val);
  }

}
