/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class ModulesList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ModulesList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModulesList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_ModulesList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ModulesList() {
    this(eufeJNI.new_ModulesList(), true);
  }

  public long size() {
    return eufeJNI.ModulesList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return eufeJNI.ModulesList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    eufeJNI.ModulesList_clear(swigCPtr, this);
  }

  public void add(Module x) {
    eufeJNI.ModulesList_add(swigCPtr, this, Module.getCPtr(x), x);
  }

  public Module get(int i) {
    long cPtr = eufeJNI.ModulesList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

}
