/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class Module extends Item {
  private long swigCPtr;

  protected Module(long cPtr, boolean cMemoryOwn) {
    super(eufeJNI.Module_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Module obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_Module(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Attribute getAttribute(int attributeID) {
    long cPtr = eufeJNI.Module_getAttribute(swigCPtr, this, attributeID);
    return (cPtr == 0) ? null : new Attribute(cPtr, false);
  }

  public Module.Slot getSlot() {
    return Module.Slot.swigToEnum(eufeJNI.Module_getSlot(swigCPtr, this));
  }

  public Module.Hardpoint getHardpoint() {
    return Module.Hardpoint.swigToEnum(eufeJNI.Module_getHardpoint(swigCPtr, this));
  }

  public boolean canHaveState(Module.State state) {
    return eufeJNI.Module_canHaveState(swigCPtr, this, state.swigValue());
  }

  public Module.State getState() {
    return Module.State.swigToEnum(eufeJNI.Module_getState(swigCPtr, this));
  }

  public void setState(Module.State state) {
    eufeJNI.Module_setState(swigCPtr, this, state.swigValue());
  }

  public SWIGTYPE_p_eufe__Charge setCharge(int typeID) {
    long cPtr = eufeJNI.Module_setCharge(swigCPtr, this, typeID);
    return (cPtr == 0) ? null : new SWIGTYPE_p_eufe__Charge(cPtr, false);
  }

  public void clearCharge() {
    eufeJNI.Module_clearCharge(swigCPtr, this);
  }

  public SWIGTYPE_p_eufe__Charge getCharge() {
    long cPtr = eufeJNI.Module_getCharge(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_eufe__Charge(cPtr, false);
  }

  public TypesList getChargeGroups() {
    return new TypesList(eufeJNI.Module_getChargeGroups(swigCPtr, this), false);
  }

  public int getChargeSize() {
    return eufeJNI.Module_getChargeSize(swigCPtr, this);
  }

  public void removeCharge() {
    eufeJNI.Module_removeCharge(swigCPtr, this);
  }

  public boolean canFit(SWIGTYPE_p_eufe__Charge charge) {
    return eufeJNI.Module_canFit(swigCPtr, this, SWIGTYPE_p_eufe__Charge.getCPtr(charge));
  }

  public boolean requireTarget() {
    return eufeJNI.Module_requireTarget(swigCPtr, this);
  }

  public void setTarget(Ship target) {
    eufeJNI.Module_setTarget__SWIG_0(swigCPtr, this, Ship.getCPtr(target), target);
  }

  public void setTarget() {
    eufeJNI.Module_setTarget__SWIG_1(swigCPtr, this);
  }

  public void clearTarget() {
    eufeJNI.Module_clearTarget(swigCPtr, this);
  }

  public Ship getTarget() {
    long cPtr = eufeJNI.Module_getTarget(swigCPtr, this);
    return (cPtr == 0) ? null : new Ship(cPtr, false);
  }

  public float getReloadTime() {
    return eufeJNI.Module_getReloadTime(swigCPtr, this);
  }

  public float getCycleTime() {
    return eufeJNI.Module_getCycleTime(swigCPtr, this);
  }

  public float getRawCycleTime() {
    return eufeJNI.Module_getRawCycleTime(swigCPtr, this);
  }

  public int getCharges() {
    return eufeJNI.Module_getCharges(swigCPtr, this);
  }

  public int getShots() {
    return eufeJNI.Module_getShots(swigCPtr, this);
  }

  public float getCapUse() {
    return eufeJNI.Module_getCapUse(swigCPtr, this);
  }

  public float getVolley() {
    return eufeJNI.Module_getVolley(swigCPtr, this);
  }

  public float getDps() {
    return eufeJNI.Module_getDps(swigCPtr, this);
  }

  public float getMaxRange() {
    return eufeJNI.Module_getMaxRange(swigCPtr, this);
  }

  public float getFalloff() {
    return eufeJNI.Module_getFalloff(swigCPtr, this);
  }

  public float getTrackingSpeed() {
    return eufeJNI.Module_getTrackingSpeed(swigCPtr, this);
  }

  public float getLifeTime() {
    return eufeJNI.Module_getLifeTime(swigCPtr, this);
  }

  public void setLifeTime(float lifeTime) {
    eufeJNI.Module_setLifeTime(swigCPtr, this, lifeTime);
  }

  public final static class Slot {
    public final static Module.Slot SLOT_NONE = new Module.Slot("SLOT_NONE");
    public final static Module.Slot SLOT_HI = new Module.Slot("SLOT_HI");
    public final static Module.Slot SLOT_MED = new Module.Slot("SLOT_MED");
    public final static Module.Slot SLOT_LOW = new Module.Slot("SLOT_LOW");
    public final static Module.Slot SLOT_RIG = new Module.Slot("SLOT_RIG");
    public final static Module.Slot SLOT_SUBSYSTEM = new Module.Slot("SLOT_SUBSYSTEM");
    public final static Module.Slot SLOT_STRUCTURE = new Module.Slot("SLOT_STRUCTURE");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Slot swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Slot.class + " with value " + swigValue);
    }

    private Slot(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Slot(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Slot(String swigName, Slot swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Slot[] swigValues = { SLOT_NONE, SLOT_HI, SLOT_MED, SLOT_LOW, SLOT_RIG, SLOT_SUBSYSTEM, SLOT_STRUCTURE };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class State {
    public final static Module.State STATE_OFFLINE = new Module.State("STATE_OFFLINE");
    public final static Module.State STATE_ONLINE = new Module.State("STATE_ONLINE");
    public final static Module.State STATE_ACTIVE = new Module.State("STATE_ACTIVE");
    public final static Module.State STATE_OVERLOADED = new Module.State("STATE_OVERLOADED");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static State swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + State.class + " with value " + swigValue);
    }

    private State(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private State(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private State(String swigName, State swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static State[] swigValues = { STATE_OFFLINE, STATE_ONLINE, STATE_ACTIVE, STATE_OVERLOADED };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class Hardpoint {
    public final static Module.Hardpoint HARDPOINT_NONE = new Module.Hardpoint("HARDPOINT_NONE", eufeJNI.Module_HARDPOINT_NONE_get());
    public final static Module.Hardpoint HARDPOINT_LAUNCHER = new Module.Hardpoint("HARDPOINT_LAUNCHER");
    public final static Module.Hardpoint HARDPOINT_TURRET = new Module.Hardpoint("HARDPOINT_TURRET");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Hardpoint swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Hardpoint.class + " with value " + swigValue);
    }

    private Hardpoint(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Hardpoint(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Hardpoint(String swigName, Hardpoint swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Hardpoint[] swigValues = { HARDPOINT_NONE, HARDPOINT_LAUNCHER, HARDPOINT_TURRET };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
