/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class Resistances {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Resistances(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Resistances obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_Resistances(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setArmor(ResistancesLayer value) {
    eufeJNI.Resistances_armor_set(swigCPtr, this, ResistancesLayer.getCPtr(value), value);
  }

  public ResistancesLayer getArmor() {
    long cPtr = eufeJNI.Resistances_armor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ResistancesLayer(cPtr, false);
  }

  public void setHull(ResistancesLayer value) {
    eufeJNI.Resistances_hull_set(swigCPtr, this, ResistancesLayer.getCPtr(value), value);
  }

  public ResistancesLayer getHull() {
    long cPtr = eufeJNI.Resistances_hull_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ResistancesLayer(cPtr, false);
  }

  public void setShield(ResistancesLayer value) {
    eufeJNI.Resistances_shield_set(swigCPtr, this, ResistancesLayer.getCPtr(value), value);
  }

  public ResistancesLayer getShield() {
    long cPtr = eufeJNI.Resistances_shield_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ResistancesLayer(cPtr, false);
  }

  public Resistances() {
    this(eufeJNI.new_Resistances(), true);
  }

}
