/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class Skill extends Item {
  private long swigCPtr;

  protected Skill(long cPtr, boolean cMemoryOwn) {
    super(eufeJNI.Skill_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Skill obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_Skill(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean isLearned() {
    return eufeJNI.Skill_isLearned(swigCPtr, this);
  }

  public int getSkillLevel() {
    return eufeJNI.Skill_getSkillLevel(swigCPtr, this);
  }

  public void setSkillLevel(int level) {
    eufeJNI.Skill_setSkillLevel(swigCPtr, this, level);
  }

}
