/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class Structure extends Module {
  private long swigCPtr;

  protected Structure(long cPtr, boolean cMemoryOwn) {
    super(eufeJNI.Structure_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Structure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_Structure(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Resistances getResistances() {
    return new Resistances(eufeJNI.Structure_getResistances(swigCPtr, this), false);
  }

  public Tank getTank() {
    return new Tank(eufeJNI.Structure_getTank(swigCPtr, this), false);
  }

  public Tank getEffectiveTank() {
    return new Tank(eufeJNI.Structure_getEffectiveTank(swigCPtr, this), false);
  }

  public HitPoints getHitPoints() {
    return new HitPoints(eufeJNI.Structure_getHitPoints(swigCPtr, this), false);
  }

  public HitPoints getEffectiveHitPoints() {
    return new HitPoints(eufeJNI.Structure_getEffectiveHitPoints(swigCPtr, this), false);
  }

  public float getShieldRecharge() {
    return eufeJNI.Structure_getShieldRecharge(swigCPtr, this);
  }

}
