/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class Tank {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Tank(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tank obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_Tank(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setArmorRepair(float value) {
    eufeJNI.Tank_armorRepair_set(swigCPtr, this, value);
  }

  public float getArmorRepair() {
    return eufeJNI.Tank_armorRepair_get(swigCPtr, this);
  }

  public void setHullRepair(float value) {
    eufeJNI.Tank_hullRepair_set(swigCPtr, this, value);
  }

  public float getHullRepair() {
    return eufeJNI.Tank_hullRepair_get(swigCPtr, this);
  }

  public void setShieldRepair(float value) {
    eufeJNI.Tank_shieldRepair_set(swigCPtr, this, value);
  }

  public float getShieldRepair() {
    return eufeJNI.Tank_shieldRepair_get(swigCPtr, this);
  }

  public void setPassiveShield(float value) {
    eufeJNI.Tank_passiveShield_set(swigCPtr, this, value);
  }

  public float getPassiveShield() {
    return eufeJNI.Tank_passiveShield_get(swigCPtr, this);
  }

  public Tank() {
    this(eufeJNI.new_Tank(), true);
  }

}
