/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.shimanski.eufe;

public class TypesList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TypesList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypesList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        eufeJNI.delete_TypesList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TypesList() {
    this(eufeJNI.new_TypesList__SWIG_0(), true);
  }

  public TypesList(long n) {
    this(eufeJNI.new_TypesList__SWIG_1(n), true);
  }

  public long size() {
    return eufeJNI.TypesList_size(swigCPtr, this);
  }

  public long capacity() {
    return eufeJNI.TypesList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    eufeJNI.TypesList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return eufeJNI.TypesList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    eufeJNI.TypesList_clear(swigCPtr, this);
  }

  public void add(int x) {
    eufeJNI.TypesList_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return eufeJNI.TypesList_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    eufeJNI.TypesList_set(swigCPtr, this, i, val);
  }

}
